import argentina from '../assets/Icon/Flag/argentina.png'
import australia from '../assets/Icon/Flag/australia.png'
import brazil from '../assets/Icon/Flag/brazil.png'
import canada from '../assets/Icon/Flag/canada.png'
import china from '../assets/Icon/Flag/china.png'
import france from '../assets/Icon/Flag/france.png'
import germany from '../assets/Icon/Flag/germany.png'
import india from '../assets/Icon/Flag/india.png'
import indonesia from '../assets/Icon/Flag/indonesia.png'
import italy from '../assets/Icon/Flag/italy.png'
import japan from '../assets/Icon/Flag/japan.png'
import malaysia from '../assets/Icon/Flag/malaysia.png'
import thailand from '../assets/Icon/Flag/thailand.png'
import turkey from '../assets/Icon/Flag/turkey.png'
import united_states from '../assets/Icon/Flag/united_states.png'
import mexico from '../assets/Icon/Flag/mexico.png'
import netherlands from '../assets/Icon/Flag/netherlands.png'
import peru from '../assets/Icon/Flag/peru.png'
import russia from '../assets/Icon/Flag/russia.png'
import saudi_arabia from '../assets/Icon/Flag/saudi arabia.png'
import south_africa from '../assets/Icon/Flag/south africa.png'
import south_korea from '../assets/Icon/Flag/south korea.png'
import spain from '../assets/Icon/Flag/spain.png'
import switzerland from '../assets/Icon/Flag/switzerland.png'
import sweden from '../assets/Icon/Flag/sweden.png'
import norway from '../assets/Icon/Flag/norway.png'
import portugal from '../assets/Icon/Flag/portugal.png'

export const Countries = [
    {
        id: 1,
        country: 'Argentina',
        phone_code: '+54',
        flag_icon: argentina,
        currency: 'Argentine Peso',
        currency_code: 'ARS',
        states: [
            { id: 1, state: 'Buenos Aires' },
            { id: 2, state: 'Córdoba' },
            { id: 3, state: 'Santa Fe' },
            { id: 4, state: 'Mendoza' },
            { id: 5, state: 'Tucumán' },
        ],
    },
    {
        id: 2,
        country: 'Australia',
        phone_code: '+61',
        flag_icon: australia,
        currency: 'Australian Dollar',
        currency_code: 'AUD',
        states: [
            { id: 1, state: 'New South Wales' },
            { id: 2, state: 'Victoria' },
            { id: 3, state: 'Queensland' },
            { id: 4, state: 'Western Australia' },
            { id: 5, state: 'South Australia' },
        ],
    },
    {
        id: 3,
        country: 'Brazil',
        phone_code: '+55',
        flag_icon: brazil,
        currency: 'Brazilian Real',
        currency_code: 'BRL',
        states: [
            { id: 1, state: 'São Paulo' },
            { id: 2, state: 'Rio de Janeiro' },
            { id: 3, state: 'Minas Gerais' },
            { id: 4, state: 'Bahia' },
            { id: 5, state: 'Paraná' },
        ],
    },
    {
        id: 4,
        country: 'Canada',
        phone_code: '+1',
        flag_icon: canada,
        currency: 'Canadian Dollar',
        currency_code: 'CAD',
        states: [
            { id: 1, state: 'Ontario' },
            { id: 2, state: 'Quebec' },
            { id: 3, state: 'British Columbia' },
            { id: 4, state: 'Alberta' },
            { id: 5, state: 'Manitoba' },
        ],
    },
    {
        id: 5,
        country: 'China',
        phone_code: '+86',
        flag_icon: china,
        currency: 'Chinese Yuan',
        currency_code: 'CNY',
        states: [
            { id: 1, state: 'Guangdong' },
            { id: 2, state: 'Beijing' },
            { id: 3, state: 'Shanghai' },
            { id: 4, state: 'Zhejiang' },
            { id: 5, state: 'Sichuan' },
        ],
    },
    {
        id: 6,
        country: 'France',
        phone_code: '+33',
        flag_icon: france,
        currency: 'Euro',
        currency_code: 'EUR',
        states: [
            { id: 1, state: 'Île-de-France' },
            { id: 2, state: "Provence-Alpes-Côte d'Azur" },
            { id: 3, state: 'Nouvelle-Aquitaine' },
            { id: 4, state: 'Auvergne-Rhône-Alpes' },
            { id: 5, state: 'Occitanie' },
        ],
    },
    {
        id: 7,
        country: 'Germany',
        phone_code: '+49',
        flag_icon: germany,
        currency: 'Euro',
        currency_code: 'EUR',
        states: [
            { id: 1, state: 'Bavaria' },
            { id: 2, state: 'North Rhine-Westphalia' },
            { id: 3, state: 'Baden-Württemberg' },
            { id: 4, state: 'Hesse' },
            { id: 5, state: 'Saxony' },
        ],
    },
    {
        id: 8,
        country: 'India',
        phone_code: '+91',
        flag_icon: india,
        currency: 'Indian Rupee',
        currency_code: 'INR',
        states: [
            { id: 1, state: 'Maharashtra' },
            { id: 2, state: 'Karnataka' },
            { id: 3, state: 'Tamil Nadu' },
            { id: 4, state: 'West Bengal' },
            { id: 5, state: 'Uttar Pradesh' },
        ],
    },
    {
        id: 9,
        country: 'Indonesia',
        phone_code: '+62',
        flag_icon: indonesia,
        currency: 'Indonesian Rupiah',
        currency_code: 'IDR',
        states: [
            { id: 1, state: 'Jakarta' },
            { id: 2, state: 'West Java' },
            { id: 3, state: 'Central Java' },
            { id: 4, state: 'East Java' },
            { id: 5, state: 'Bali' },
        ],
    },
    {
        id: 10,
        country: 'Italy',
        phone_code: '+39',
        flag_icon: italy,
        currency: 'Euro',
        currency_code: 'EUR',
        states: [
            { id: 1, state: 'Lombardy' },
            { id: 2, state: 'Lazio' },
            { id: 3, state: 'Campania' },
            { id: 4, state: 'Sicily' },
            { id: 5, state: 'Veneto' },
        ],
    },
    {
        id: 11,
        country: 'Japan',
        phone_code: '+81',
        flag_icon: japan,
        currency: 'Japanese Yen',
        currency_code: 'JPY',
        states: [
            { id: 1, state: 'Tokyo' },
            { id: 2, state: 'Osaka' },
            { id: 3, state: 'Kanagawa' },
            { id: 4, state: 'Hokkaido' },
            { id: 5, state: 'Aichi' },
        ],
    },
    {
        id: 12,
        country: 'Malaysia',
        phone_code: '+60',
        flag_icon: malaysia,
        currency: 'Malaysian Ringgit',
        currency_code: 'MYR',
        states: [
            { id: 1, state: 'Selangor' },
            { id: 2, state: 'Penang' },
            { id: 3, state: 'Johor' },
            { id: 4, state: 'Perak' },
            { id: 5, state: 'Sarawak' },
        ],
    },
    {
        id: 13,
        country: 'Mexico',
        phone_code: '+52',
        flag_icon: mexico,
        currency: 'Mexican Peso',
        currency_code: 'MXN',
        states: [
            { id: 1, state: 'Mexico City' },
            { id: 2, state: 'Jalisco' },
            { id: 3, state: 'Nuevo León' },
            { id: 4, state: 'Puebla' },
            { id: 5, state: 'Guanajuato' },
        ],
    },
    {
        id: 14,
        country: 'Netherlands',
        phone_code: '+31',
        flag_icon: netherlands,
        currency: 'Euro',
        currency_code: 'EUR',
        states: [
            { id: 1, state: 'North Holland' },
            { id: 2, state: 'South Holland' },
            { id: 3, state: 'Utrecht' },
            { id: 4, state: 'North Brabant' },
            { id: 5, state: 'Gelderland' },
        ],
    },
    {
        id: 15,
        country: 'Norway',
        phone_code: '+47',
        flag_icon: peru,
        currency: 'Norwegian Krone',
        currency_code: 'NOK',
        states: [
            { id: 1, state: 'Oslo' },
            { id: 2, state: 'Bergen' },
            { id: 3, state: 'Trondheim' },
            { id: 4, state: 'Stavanger' },
            { id: 5, state: 'Kristiansand' },
        ],
    },
    {
        id: 16,
        country: 'Russia',
        phone_code: '+7',
        flag_icon: russia,
        currency: 'Russian Ruble',
        currency_code: 'RUB',
        states: [
            { id: 1, state: 'Moscow' },
            { id: 2, state: 'Saint Petersburg' },
            { id: 3, state: 'Novosibirsk' },
            { id: 4, state: 'Yekaterinburg' },
            { id: 5, state: 'Nizhny Novgorod' },
        ],
    },
    {
        id: 17,
        country: 'Saudi Arabia',
        phone_code: '+966',
        flag_icon: saudi_arabia,
        currency: 'Saudi Riyal',
        currency_code: 'SAR',
        states: [
            { id: 1, state: 'Riyadh' },
            { id: 2, state: 'Jeddah' },
            { id: 3, state: 'Mecca' },
            { id: 4, state: 'Medina' },
            { id: 5, state: 'Dammam' },
        ],
    },
    {
        id: 18,
        country: 'South Africa',
        phone_code: '+27',
        flag_icon: south_africa,
        currency: 'South African Rand',
        currency_code: 'ZAR',
        states: [
            { id: 1, state: 'Gauteng' },
            { id: 2, state: 'Western Cape' },
            { id: 3, state: 'KwaZulu-Natal' },
            { id: 4, state: 'Eastern Cape' },
            { id: 5, state: 'Mpumalanga' },
        ],
    },
    {
        id: 19,
        country: 'South Korea',
        phone_code: '+82',
        flag_icon: south_korea,
        currency: 'South Korean Won',
        currency_code: 'KRW',
        states: [
            { id: 1, state: 'Seoul' },
            { id: 2, state: 'Busan' },
            { id: 3, state: 'Incheon' },
            { id: 4, state: 'Daegu' },
            { id: 5, state: 'Gwangju' },
        ],
    },
    {
        id: 20,
        country: 'Spain',
        phone_code: '+34',
        flag_icon: spain,
        currency: 'Euro',
        currency_code: 'EUR',
        states: [
            { id: 1, state: 'Madrid' },
            { id: 2, state: 'Catalonia' },
            { id: 3, state: 'Andalusia' },
            { id: 4, state: 'Valencia' },
            { id: 5, state: 'Galicia' },
        ],
    },
    {
        id: 21,
        country: 'Sweden',
        phone_code: '+46',
        flag_icon: sweden,
        currency: 'Swedish Krona',
        currency_code: 'SEK',
        states: [
            { id: 1, state: 'Stockholm' },
            { id: 2, state: 'Gothenburg' },
            { id: 3, state: 'Skåne' },
            { id: 4, state: 'Uppsala' },
            { id: 5, state: 'Västra Götaland' },
        ],
    },
    {
        id: 22,
        country: 'Switzerland',
        phone_code: '+41',
        flag_icon: switzerland,
        currency: 'Swiss Franc',
        currency_code: 'CHF',
        states: [
            { id: 1, state: 'Zurich' },
            { id: 2, state: 'Geneva' },
            { id: 3, state: 'Bern' },
            { id: 4, state: 'Basel' },
            { id: 5, state: 'Vaud' },
        ],
    },
    {
        id: 23,
        country: 'Thailand',
        phone_code: '+66',
        flag_icon: thailand,
        currency: 'Thai Baht',
        currency_code: 'THB',
        states: [
            { id: 1, state: 'Bangkok' },
            { id: 2, state: 'Chiang Mai' },
            { id: 3, state: 'Phuket' },
            { id: 4, state: 'Chonburi' },
            { id: 5, state: 'Nakhon Ratchasima' },
        ],
    },
    {
        id: 24,
        country: 'Turkey',
        phone_code: '+90',
        flag_icon: turkey,
        currency: 'Turkish Lira',
        currency_code: 'TRY',
        states: [
            { id: 1, state: 'Istanbul' },
            { id: 2, state: 'Ankara' },
            { id: 3, state: 'Izmir' },
            { id: 4, state: 'Antalya' },
            { id: 5, state: 'Bursa' },
        ],
    },
    {
        id: 25,
        country: 'United States',
        phone_code: '+1',
        flag_icon: united_states,
        currency: 'US Dollar',
        currency_code: 'USD',
        states: [
            { id: 1, state: 'California' },
            { id: 2, state: 'Texas' },
            { id: 3, state: 'New York' },
            { id: 4, state: 'Florida' },
            { id: 5, state: 'Illinois' },
        ],
    },
]

export const Language = [
    {
        id: 1,
        language: 'Arabic',
        language_code: 'ARB',
        flag_icon: saudi_arabia,
    },
    { id: 2, language: 'Chinese', language_code: 'CHI', flag_icon: china },
    {
        id: 3,
        language: 'Dutch',
        language_code: 'DTH',
        flag_icon: netherlands,
    },
    {
        id: 4,
        language: 'English',
        language_code: 'ENG',
        flag_icon: united_states,
    },
    { id: 5, language: 'French', language_code: 'FRC', flag_icon: france },
    { id: 6, language: 'German', language_code: 'GER', flag_icon: germany },
    { id: 7, language: 'Hindi', language_code: 'NIN', flag_icon: india },
    {
        id: 8,
        language: 'Indonesian',
        language_code: 'IND',
        flag_icon: indonesia,
    },
    { id: 9, language: 'Italian', language_code: 'ITN', flag_icon: italy },
    {
        id: 10,
        language: 'Japanese',
        language_code: 'JPN',
        flag_icon: japan,
    },
    {
        id: 11,
        language: 'Korea',
        language_code: 'KOR',
        flag_icon: south_korea,
    },
    {
        id: 12,
        language: 'Malay',
        language_code: 'MLY',
        flag_icon: malaysia,
    },
    {
        id: 13,
        language: 'Norwegian',
        language_code: 'NOR',
        flag_icon: norway,
    },
    {
        id: 14,
        language: 'Portuguese',
        language_code: 'POR',
        flag_icon: portugal,
    },
    {
        id: 15,
        language: 'Russian',
        language_code: 'RUS',
        flag_icon: russia,
    },
    { id: 16, language: 'Spanish', language_code: 'SPN', flag_icon: spain },
    {
        id: 17,
        language: 'Swedish',
        language_code: 'SWD',
        flag_icon: sweden,
    },
    { id: 18, language: 'Thai', language_code: 'THI', flag_icon: thailand },
    {
        id: 19,
        language: 'Turkish',
        language_code: 'TUR',
        flag_icon: turkey,
    },
]
